on: pull_request
name: run_tests
jobs:
  setup_project:
    name: Setup metaQASM and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
      - uses: freckle/stack-action@v5
        with:
          install-stack: false
          upgrade-stack: false
          stack-build-arguments: false

#      - run: stack test
